---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse

- name: Configure clickhouse
  hosts: clickhouse
  tasks:
    - name: Create DB
      become: true
      ansible.builtin.command: clickhouse-client --query "CREATE DATABASE IF NOT EXISTS nginxdb"

    - name: Create table
      become: true
      ansible.builtin.command: clickhouse-client --query "CREATE TABLE IF NOT EXISTS  nginxdb.access_logs ( message String ) ENGINE = MergeTree() ORDER BY tuple()"


- name: Install Vector
  hosts: vector
  roles:
    - vector-role


- name: Install nginx for lighthouse
  hosts: lighthouse
  roles:
    - lighthouse-role







