apiVersion: v1
kind: Service
metadata:
  name: nginx-and-multitool-svc
spec:
  ports:
  - name: nginx
    port: 80
    protocol: TCP
    targetPort: 80
  - name: multitool
    port: 1180
    protocol: TCP
    targetPort: 1180
  selector:
    app: nginx-and-multitool
