apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
         - containerPort: 80
      initContainers:
      - name: check-svc
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup nginx-svc; do echo waiting for nginx-svc; sleep 2; done"]
