namespace: my_own_namespace

name: yandex_cloud_elk

version: 1.0.0

readme: README.md

authors:
- Ivan Titovich (i.a.titovich@gmail.com)

description: Testing collection.

license:
- GPL-2.0-or-later

license_file: ''

tags: []

dependencies: {}

repository: http://example.com/repository

documentation: http://docs.example.com

homepage: http://example.com

issues: http://example.com/issue/tracker

build_ignore: []

