stages:
  - build
  - test
  - deploy

image: docker:20.10.5
services:
  - docker:20.10.5-dind


builder:
    stage: build
    script:
        - echo " building for devops"
        - docker build -t python-api:latest  .
    except:
        - main
deployer:
    stage: deploy
    script:
        - echo " deploying for developer"
        - docker build -t python-api:latest .
        #- docker build -t $CI_REGISTRY/ivan-titovich/09-ci-06/python-api:latest .
        #- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        #- docker push $CI_REGISTRY/ivan-titovich/09-ci-06/python-api:latest
    only:
        - main
