apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  namespace: dev
  labels:
    name: deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: deploy

  template:
    metadata:
      labels:
        name: deploy
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        env:
          - name: HTTP_PORT
            valueFrom:
              configMapKeyRef:
                name: deploy-cm
                key: "HTTP_PORT"

          - name: HTTPS_PORT
            valueFrom:
              configMapKeyRef:
                name: deploy-cm
                key: "HTTPS_PORT"

