---
  el:
    hosts:
      centos7:
        ansible_connection: local
  deb:
    hosts:
      ubuntu:
        ansible_connection: docker
        hosts:
          - 172.17.0.2
        ansible_user: "root"
        ansible_ssh_pass: "root"
        ansible_password: "root"

