apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
spec:
  ports:
  - name: nginx
    port: 9001
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  - name: multitool
    port: 9002
    protocol: TCP
    targetPort: 8080
    nodePort: 30088
  selector:
    app: nginx-and-multitool
  type: NodePort
