apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  capacity:
    storage: 1Gi
#  volumeMode: Filesystem
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
#  storageClassName: local-storage
  storageClassName: microk8s-hostpath
#  local:
#    path: /tmp/vol1
  hostPath:
    path: /tmp/vol1


