---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 51.250.80.71


vector:
  hosts:
    vector-01:
      ansible_host: 51.250.80.71

lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 51.250.80.71



