apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds
  labels:
    app: ds
spec:
  selector:
    matchLabels:
      app: ds

  template:
    metadata:
      labels:
        app: ds
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        env:
          - name: HTTP_PORT
            value: "10080"
          - name: HTTPS_PORT
            value: "12443"
        volumeMounts:
        - name: varlog
          mountPath: "/var/log/syslog"
      volumes:
      - name: varlog
        hostPath:
          path: /var/log/syslog



