apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-page
data:
  index.html:  |
    <!DOCTYPE html>
    <html>
    <head>
    <title>This is demo-page for demonstrating ConfigMap!</title>
    <style>
    html { color-scheme: light dark; }
    body { width: 35em; margin: 0 auto;
    font-family: Tahoma, Verdana, Arial, sans-serif; }
    </style>
    </head>
    <body>
    <h1>This is demo-page for demonstrating ConfigMap</h1>
    <p>Homework by Titovich Ivan.</p>

    <p><em>Thank you for watching my homework.</em></p>
    </body>
    </html>
