apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf:  |
    server {
      listen   80;
      listen  [::]:80;
      server_name 10.152.183.107;
      ssl_certificate /etc/nginx/ssl/nginx-selfsigned.crt;
      ssl_certificate_key /etc/nginx/ssl/nginx-selfsigned.key;
      
      listen 443 ssl http2;
  
      #access_log  /var/log/nginx/host.access.log  main;
  
      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }

      
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
  
    }

