apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
type: opaque
data:
  nginx-selfsigned.crt:  |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURuVENDQW9XZ0F3SUJBZ0lVQmZNaVBwVDBt
    L2RvSldOVWxUdStwS0ZudVhBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1hqRUxNQWtHQTFVRUJoTUNV
    bFV4RXpBUkJnTlZCQWdNQ2xOdmJXVXRVM1JoZEdVeElUQWZCZ05WQkFvTQpHRWx1ZEdWeWJtVjBJ
    RmRwWkdkcGRITWdVSFI1SUV4MFpERVhNQlVHQTFVRUF3d09NVEF1TVRVeUxqRTRNeTR4Ck1EY3dI
    aGNOTWpNd01qRTJNVGcwT1RBeVdoY05NalF3TWpFMk1UZzBPVEF5V2pCZU1Rc3dDUVlEVlFRR0V3
    SlMKVlRFVE1CRUdBMVVFQ0F3S1UyOXRaUzFUZEdGMFpURWhNQjhHQTFVRUNnd1lTVzUwWlhKdVpY
    UWdWMmxrWjJsMApjeUJRZEhrZ1RIUmtNUmN3RlFZRFZRUUREQTR4TUM0eE5USXVNVGd6TGpFd056
    Q0NBU0l3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFLc05IaUVhcFZtWUhG
    M2Fjb1JJTmV2bFFKc2pOMlhhd1VXTlFZc2wKWVZsc0dpaFUxM2g2WmFjQjZkQ0NlK2VIZlBXYjBi
    cVNGOFR1b1RLYmdwV0RFS3V0Rzg2OHIrc2VjcXExMFNyNgo5dlJ2blpPeFlpUWtZYXJjQzlLVkRw
    T01hRmd2SWpRKzB2cUlDUDFYVDJJb2lEYU13d0RaT1FaUysycEEzWGdvCmJNN0VnT0hvMUNOcERR
    bktnbXdScU9EcUNNNlhob0VYYVZvakZFVjQyUzlidjhZOU53UnBYWitObW9xQzF3b0kKZFdXdVgz
    anVJbTgwblpMNW9hSk84THk4VkxzRWZtQlJUVDlSbmQvdkJNeEt5TGdHNm92T1dBNFd2QVFuWW00
    VgpUTFNHMWhJZ0xmOGs1NU8rZzBKdHA2TWJldmFVRjNKc0pzbGJxVWxiMEFKZ2djRUNBd0VBQWFO
    VE1GRXdIUVlEClZSME9CQllFRk5od0RzcklPb0tpanU5U3Q0T2Nzd0hDQ1hCcU1COEdBMVVkSXdR
    WU1CYUFGTmh3RHNySU9vS2kKanU5U3Q0T2Nzd0hDQ1hCcU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4
    d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQgpBRVMrTFR6NGJzWHJ3c3JCM1QyaW8xUGRVTnpBS0Zs
    VkkrM0hpbDZhTUVtRXRLZ1ZGZ1djMEhtMm00SzhNZ3JtCmNubjZnOGk4ZGdPcStwZlFJcGdjUytB
    dWxvWUN1dEE5YlIwZ2xOSHRJN1AwbkN6SzBtdFUrZU8zM2Zhb1VVVXYKc016WDcydXFJdEtDeTcw
    YTNRYzBIRDJVMXJZcWZZWFFpcnVVSURFaGFTbEExOWZISVdwdlBCUTlLZFc5aGYzbQpzanZaUERt
    aXB4N0k5ZDhiN3VxUVV2MkhYMEJQSGVLNWlaeFhUWkQvNUVXQ1RIckZnbFpkMVNkVVYwUEUyOXU2
    Cm91cithZ3NsaVFUZUliQUlBTDQ2QVhxVEhnZzBWMzcyR3ZWclhyQXdoTlB3TVNPajByWWdwTm9n
    YllpWTg5LzcKTUFrRUMyTkZrRElXZ3YwM1krTFlCVmc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0t
    LS0K
  nginx-selfsigned.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktZd2dnU2lBZ0VBQW9JQkFRQ3JEUjRoR3FWWm1CeGQKMm5LRVNEWHI1VUNiSXpkbDJzRkZq
    VUdMSldGWmJCb29WTmQ0ZW1XbkFlblFnbnZuaDN6MW05RzZraGZFN3FFeQptNEtWZ3hDcnJSdk92
    Sy9ySG5LcXRkRXErdmIwYjUyVHNXSWtKR0dxM0F2U2xRNlRqR2hZTHlJMFB0TDZpQWo5ClYwOWlL
    SWcyak1NQTJUa0dVdnRxUU4xNEtHek94SURoNk5RamFRMEp5b0pzRWFqZzZnak9sNGFCRjJsYUl4
    UkYKZU5rdlc3L0dQVGNFYVYyZmpacUtndGNLQ0hWbHJsOTQ3aUp2TkoyUythR2lUdkM4dkZTN0JI
    NWdVVTAvVVozZgo3d1RNU3NpNEJ1cUx6bGdPRnJ3RUoySnVGVXkwaHRZU0lDMy9KT2VUdm9OQ2Jh
    ZWpHM3IybEJkeWJDYkpXNmxKClc5QUNZSUhCQWdNQkFBRUNnZ0VBSWx2NXMrT2kyRXJ1VThuNEcr
    dFhiWUc1QnhDOVpZZmFMK3J1Z2hGcHF5bEUKWGRxaEI3SHFibkE3YytkcUZUbUpsOXFMZUFNMXBC
    amRKNG5HWXRzWGc2eTd1N3o2UjJ2djA2dS9EdmVubUxVOAovWGh4d3RuT0JxQzUvVHgwMTUycUxp
    Q1ZxZEgrMWxWeUhOV25mQXV4Uk9ma21leUlnR1UxM0lPWUdUVmhtZXpaCnd2Y0lqUUo0N1d5V3Bl
    NGxucmNZZS9CL2FOa3dlVG1XNDBGZC9TRnJ6dmJDdlQwT0tmZElYc0luaXo5VGQzd0YKWlR3ajhi
    T2R6cnN6czRVK1hUeWkwaWZWWkNGeXB3ZjNRVk1GZy83d3JObTFobytsVE14S2RTdlI4a1J1N3N1
    dwpKM1BiS1JxTUNUZXUzWG1YanEzVklpZjQ3WXpWU2RKRHZINElpbHBUbVFLQmdRRGdWR1NoMWpo
    SWx3S2gxSVkyCnNxS2J4NHFXclVFU1BpcytHa0FnemMrdTdIUHF1OW9tSmhoYkNXOS9FUXVPY1ZO
    S0poUmxMa25YUTIrKzRWU1oKVThWSU9ycnREWm1WN2tTaVR3RXg0cnhVSkJjVVNYdXI3bG5PSGVZ
    T3I1dkFrN09wKzFuamN1MkhrSCtpT1lsaQpaRytEdS93THpldzZvcjdCdjVXYXBhWjY5UUtCZ1FE
    RE15blcyRlB2NXlxTHpsYW1CSFNuYWdoQTB2WFR3dVMxCmd3dW9senJ2OHk2SCtVTDlSWDBzODZJ
    RHlyQmVDWWh4cUx2eHRBSXJGWVZFd2k5RVFYKzNRemtpZXZJQUxCNjQKeURnUUlQV3NOVG5vK3dV
    ZEhoQlpRMHBSbC9IRkZQRGVHMWdnUmJxNDBZbHFOSmFWQndkSjlvOG9LM1lUZWxQegpaVGhGREQz
    RUhRS0JnSHVxNnFNeE5td0dHK1JkQmZSbmZDOUd6TWNPRWg1ZGVYZE4vMlpXTDVUdU0yVUhWRmJO
    Cmo0VzRhT2Z5M0owVkttWnBJYnM1em1sR2V2Y092NVdiVWRua3pxSGFhbjMyRVk0czRhcS9wVFQ1
    aEdPaHN2VHcKZkQrZHlmTDBxbmQ2dFlRUzFkWUd5SjJBY214YkxicTVSYVNvNEdVZGk0b3pwOWVs
    cDNMT3VUMTFBb0dBSmlhMAowYm44UmRKUG5YMlpyOThGRWNlR2oyenNBUlNCY1B5STVjMlJCbDdv
    UkVreWo1L3FSRVBsOFluSENNb2lNZHpCCnh3N2dzWjBHTEJjcjk5STViUThsZHBqQy9jZWh4WW5V
    YzBxTjJiZVpkdkRBNGgwREl2OGs0bWVwS0ZUY2N2eXoKTDdPUk9CZzBIRjdrNDRHNUtmcVhwa2xB
    VGJSRi9qZFZWU0Y4WFAwQ2dZQWRKZ2kwZzl0citYOFNNTmYzOW82Two5amlwWERkaFBnQnpkcCsv
    N3Q3TTFxUVBSR0drVnhkMUIyaGR5c0FwZ00zeHJUYkRZbnYxSmkySTZhY090eTMwCnl4MlVUd3BM
    b093UFZ1MG43UGo3dWkxczZDRk85TXo3NmVVQUpWOUVnZFNNMnhsUFBlTlg5ZnF0ZytGNFlTb0QK
    RlRuTmwzNmZsVmN0SERML3NSVHdFQT09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
    
  tls.crt:  |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURuVENDQW9XZ0F3SUJBZ0lVQmZNaVBwVDBt
    L2RvSldOVWxUdStwS0ZudVhBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1hqRUxNQWtHQTFVRUJoTUNV
    bFV4RXpBUkJnTlZCQWdNQ2xOdmJXVXRVM1JoZEdVeElUQWZCZ05WQkFvTQpHRWx1ZEdWeWJtVjBJ
    RmRwWkdkcGRITWdVSFI1SUV4MFpERVhNQlVHQTFVRUF3d09NVEF1TVRVeUxqRTRNeTR4Ck1EY3dI
    aGNOTWpNd01qRTJNVGcwT1RBeVdoY05NalF3TWpFMk1UZzBPVEF5V2pCZU1Rc3dDUVlEVlFRR0V3
    SlMKVlRFVE1CRUdBMVVFQ0F3S1UyOXRaUzFUZEdGMFpURWhNQjhHQTFVRUNnd1lTVzUwWlhKdVpY
    UWdWMmxrWjJsMApjeUJRZEhrZ1RIUmtNUmN3RlFZRFZRUUREQTR4TUM0eE5USXVNVGd6TGpFd056
    Q0NBU0l3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFLc05IaUVhcFZtWUhG
    M2Fjb1JJTmV2bFFKc2pOMlhhd1VXTlFZc2wKWVZsc0dpaFUxM2g2WmFjQjZkQ0NlK2VIZlBXYjBi
    cVNGOFR1b1RLYmdwV0RFS3V0Rzg2OHIrc2VjcXExMFNyNgo5dlJ2blpPeFlpUWtZYXJjQzlLVkRw
    T01hRmd2SWpRKzB2cUlDUDFYVDJJb2lEYU13d0RaT1FaUysycEEzWGdvCmJNN0VnT0hvMUNOcERR
    bktnbXdScU9EcUNNNlhob0VYYVZvakZFVjQyUzlidjhZOU53UnBYWitObW9xQzF3b0kKZFdXdVgz
    anVJbTgwblpMNW9hSk84THk4VkxzRWZtQlJUVDlSbmQvdkJNeEt5TGdHNm92T1dBNFd2QVFuWW00
    VgpUTFNHMWhJZ0xmOGs1NU8rZzBKdHA2TWJldmFVRjNKc0pzbGJxVWxiMEFKZ2djRUNBd0VBQWFO
    VE1GRXdIUVlEClZSME9CQllFRk5od0RzcklPb0tpanU5U3Q0T2Nzd0hDQ1hCcU1COEdBMVVkSXdR
    WU1CYUFGTmh3RHNySU9vS2kKanU5U3Q0T2Nzd0hDQ1hCcU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4
    d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQgpBRVMrTFR6NGJzWHJ3c3JCM1QyaW8xUGRVTnpBS0Zs
    VkkrM0hpbDZhTUVtRXRLZ1ZGZ1djMEhtMm00SzhNZ3JtCmNubjZnOGk4ZGdPcStwZlFJcGdjUytB
    dWxvWUN1dEE5YlIwZ2xOSHRJN1AwbkN6SzBtdFUrZU8zM2Zhb1VVVXYKc016WDcydXFJdEtDeTcw
    YTNRYzBIRDJVMXJZcWZZWFFpcnVVSURFaGFTbEExOWZISVdwdlBCUTlLZFc5aGYzbQpzanZaUERt
    aXB4N0k5ZDhiN3VxUVV2MkhYMEJQSGVLNWlaeFhUWkQvNUVXQ1RIckZnbFpkMVNkVVYwUEUyOXU2
    Cm91cithZ3NsaVFUZUliQUlBTDQ2QVhxVEhnZzBWMzcyR3ZWclhyQXdoTlB3TVNPajByWWdwTm9n
    YllpWTg5LzcKTUFrRUMyTkZrRElXZ3YwM1krTFlCVmc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0t
    LS0K
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktZd2dnU2lBZ0VBQW9JQkFRQ3JEUjRoR3FWWm1CeGQKMm5LRVNEWHI1VUNiSXpkbDJzRkZq
    VUdMSldGWmJCb29WTmQ0ZW1XbkFlblFnbnZuaDN6MW05RzZraGZFN3FFeQptNEtWZ3hDcnJSdk92
    Sy9ySG5LcXRkRXErdmIwYjUyVHNXSWtKR0dxM0F2U2xRNlRqR2hZTHlJMFB0TDZpQWo5ClYwOWlL
    SWcyak1NQTJUa0dVdnRxUU4xNEtHek94SURoNk5RamFRMEp5b0pzRWFqZzZnak9sNGFCRjJsYUl4
    UkYKZU5rdlc3L0dQVGNFYVYyZmpacUtndGNLQ0hWbHJsOTQ3aUp2TkoyUythR2lUdkM4dkZTN0JI
    NWdVVTAvVVozZgo3d1RNU3NpNEJ1cUx6bGdPRnJ3RUoySnVGVXkwaHRZU0lDMy9KT2VUdm9OQ2Jh
    ZWpHM3IybEJkeWJDYkpXNmxKClc5QUNZSUhCQWdNQkFBRUNnZ0VBSWx2NXMrT2kyRXJ1VThuNEcr
    dFhiWUc1QnhDOVpZZmFMK3J1Z2hGcHF5bEUKWGRxaEI3SHFibkE3YytkcUZUbUpsOXFMZUFNMXBC
    amRKNG5HWXRzWGc2eTd1N3o2UjJ2djA2dS9EdmVubUxVOAovWGh4d3RuT0JxQzUvVHgwMTUycUxp
    Q1ZxZEgrMWxWeUhOV25mQXV4Uk9ma21leUlnR1UxM0lPWUdUVmhtZXpaCnd2Y0lqUUo0N1d5V3Bl
    NGxucmNZZS9CL2FOa3dlVG1XNDBGZC9TRnJ6dmJDdlQwT0tmZElYc0luaXo5VGQzd0YKWlR3ajhi
    T2R6cnN6czRVK1hUeWkwaWZWWkNGeXB3ZjNRVk1GZy83d3JObTFobytsVE14S2RTdlI4a1J1N3N1
    dwpKM1BiS1JxTUNUZXUzWG1YanEzVklpZjQ3WXpWU2RKRHZINElpbHBUbVFLQmdRRGdWR1NoMWpo
    SWx3S2gxSVkyCnNxS2J4NHFXclVFU1BpcytHa0FnemMrdTdIUHF1OW9tSmhoYkNXOS9FUXVPY1ZO
    S0poUmxMa25YUTIrKzRWU1oKVThWSU9ycnREWm1WN2tTaVR3RXg0cnhVSkJjVVNYdXI3bG5PSGVZ
    T3I1dkFrN09wKzFuamN1MkhrSCtpT1lsaQpaRytEdS93THpldzZvcjdCdjVXYXBhWjY5UUtCZ1FE
    RE15blcyRlB2NXlxTHpsYW1CSFNuYWdoQTB2WFR3dVMxCmd3dW9senJ2OHk2SCtVTDlSWDBzODZJ
    RHlyQmVDWWh4cUx2eHRBSXJGWVZFd2k5RVFYKzNRemtpZXZJQUxCNjQKeURnUUlQV3NOVG5vK3dV
    ZEhoQlpRMHBSbC9IRkZQRGVHMWdnUmJxNDBZbHFOSmFWQndkSjlvOG9LM1lUZWxQegpaVGhGREQz
    RUhRS0JnSHVxNnFNeE5td0dHK1JkQmZSbmZDOUd6TWNPRWg1ZGVYZE4vMlpXTDVUdU0yVUhWRmJO
    Cmo0VzRhT2Z5M0owVkttWnBJYnM1em1sR2V2Y092NVdiVWRua3pxSGFhbjMyRVk0czRhcS9wVFQ1
    aEdPaHN2VHcKZkQrZHlmTDBxbmQ2dFlRUzFkWUd5SjJBY214YkxicTVSYVNvNEdVZGk0b3pwOWVs
    cDNMT3VUMTFBb0dBSmlhMAowYm44UmRKUG5YMlpyOThGRWNlR2oyenNBUlNCY1B5STVjMlJCbDdv
    UkVreWo1L3FSRVBsOFluSENNb2lNZHpCCnh3N2dzWjBHTEJjcjk5STViUThsZHBqQy9jZWh4WW5V
    YzBxTjJiZVpkdkRBNGgwREl2OGs0bWVwS0ZUY2N2eXoKTDdPUk9CZzBIRjdrNDRHNUtmcVhwa2xB
    VGJSRi9qZFZWU0Y4WFAwQ2dZQWRKZ2kwZzl0citYOFNNTmYzOW82Two5amlwWERkaFBnQnpkcCsv
    N3Q3TTFxUVBSR0drVnhkMUIyaGR5c0FwZ00zeHJUYkRZbnYxSmkySTZhY090eTMwCnl4MlVUd3BM
    b093UFZ1MG43UGo3dWkxczZDRk85TXo3NmVVQUpWOUVnZFNNMnhsUFBlTlg5ZnF0ZytGNFlTb0QK
    RlRuTmwzNmZsVmN0SERML3NSVHdFQT09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
