apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  ports:
  - name: nginx80
    port: 80
    protocol: TCP
    targetPort: 80
  - name: nginx443
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    name: nginx
