---
dependency:
  name: galaxy
driver:
  name: docker
  options:
    D: true
    vv: true
lint: |
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: ubuntu
    image: ubuntu:latest
    dockerfile: ../resources/Dockerfile.j2
    # pre_build_image: true
    command: /sbin/init
    privileged: true
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    env:
      ANSIBLE_USER: ansible
      SUDO_GROUP: sudo
      DEPLOY_GROUP: deployer
      container: docker
provisioner:
  name: ansible
verifier:
  name: ansible