apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-and-multitool
  labels:
    app: nginx-and-multitool
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 80%
      maxUnavailable: 80%
  selector:
    matchLabels:
      app: nginx-and-multitool

  template:
    metadata:
      labels:
        app: nginx-and-multitool
    spec:
      containers:
      - name: nginx
        image: nginx:1.28
        ports:
         - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool
        env:
          - name: HTTP_PORT
            value: "8080"

          - name: HTTPS_PORT
            value: "4443"
