apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-and-multitool
  labels:
    app: nginx-and-multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-and-multitool

  template:
    metadata:
      labels:
        app: nginx-and-multitool
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
         - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool
        env:
          - name: HTTP_PORT
            value: "1180"
          - name: HTTPS_PORT
            value: "11443"
