apiVersion: v1
kind: Pod
metadata:
  name: pod-pvc
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: "/static"
          name: static
  volumes:
    - name: static
      persistentVolumeClaim:
        claimName: pvc-capacity
