apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-capacity
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/pv-capacity
