apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: example
  namespace: default
spec:
  serviceName: example
  replicas: 3
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: example
              mountPath: /static

  volumeClaimTemplates:
  - metadata:
      name: example
    spec:
      storageClassName: rbd
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: "1Gi"
