{
 "title": "HW_Dash",
 "time": { "from": "2022-11-15T18:39:36.899Z", "to": "2022-11-15T20:21:42.749Z" },
 "panels": [
  {
   "title": "CPU - usage in percents",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (rate(node_cpu_seconds_total{job=\"nodeexporter\", mode=\"idle\"}[1m]) * 100)"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}"
    },
    {
     "expr": "node_load5{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}"
    },
    {
     "expr": "node_load15{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}"
    }
   ]
  },
  {
   "title": "Disk usage in %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{ mountpoint=\"/\",fstype!=\"rootfs\", instance=\"nodeexporter:9100\", job=\"nodeexporter\"} *100) / node_filesystem_size_bytes{ mountpoint=\"/\",fstype!=\"rootfs\",  instance=\"nodeexporter:9100\", job=\"nodeexporter\"})\n"
    }
   ]
  },
  {
   "title": "Free memory (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemAvailable_bytes{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}/node_memory_MemTotal_bytes{instance=\"nodeexporter:9100\", job=\"nodeexporter\"})*100"
    }
   ]
  }
 ]
}