---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 51.250.0.38
#      ansible_ssh_user: "vagrant"
#      ansible_ssh_password: "vagrant"

vector:
  hosts:
    vector-01:
      ansible_host: 51.250.0.38

lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 51.250.73.247
#      ansible_ssh_user: "vagrant"
#      ansible_ssh_password: "vagrant"


