apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ivan
subjects:
- kind: User
  name: ivan
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io